In [46]:
pip install --force-reinstall wheel


Note: you may need to restart the kernel to use updated packages.Collecting wheel
  Using cached wheel-0.43.0-py3-none-any.whl.metadata (2.2 kB)
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
  Attempting uninstall: wheel
    Found existing installation: wheel 0.43.0
    Uninstalling wheel-0.43.0:
      Successfully uninstalled wheel-0.43.0
  Rolling back uninstall of wheel
  Moving to c:\python312\lib\site-packages\wheel-0.43.0.dist-info\
   from C:\Python312\Lib\site-packages\~heel-0.43.0.dist-info
  Moving to c:\python312\lib\site-packages\wheel\
   from C:\Python312\Lib\site-packages\~heel



ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\Python312\\Scripts\\wheel.exe' -> 'c:\\Python312\\Scripts\\wheel.exe.deleteme'



In [47]:
!pip install spacy

In [48]:
import re
import numpy as np
import nltk
import pandas as pd
import tqdm
import spacy
nltk.download('stopwords') 
nltk.download('wordnet') 

[nltk_data] Downloading package stopwords to C:\Users\Leo
[nltk_data]     Hirano\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Leo
[nltk_data]     Hirano\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [49]:
data_tip=pd.read_json('./data/yelp_academic_dataset_tip.json', lines=True,)

In [122]:
data_review = pd.read_json('./data/yelp_academic_dataset_review.json', lines=True, nrows=2000)



In [51]:
data_business=pd.read_json('./data/yelp_academic_dataset_business.json', lines=True,)

In [52]:
pip install gensim[all]

Note: you may need to restart the kernel to use updated packages.


In [53]:
pip install scipy==1.10.1


Note: you may need to restart the kernel to use updated packages.


ERROR: Ignored the following yanked versions: 1.11.0
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python <3.12,>=3.8; 1.10.0rc1 Requires-Python <3.12,>=3.8; 1.10.0rc2 Requires-Python <3.12,>=3.8; 1.10.1 Requires-Python <3.12,>=3.8; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.12; 1.9.0rc1 Requires-Python >=3.8,<3.12; 1.9.0rc2 Requires-Python >=3.8,<3.12; 1.9.0rc3 Requires-Python >=3.8,<3.12; 1.9.1 Requires-Python >=3.8,<3.12
ERROR: Could not find a version that satisfies the requirement scipy==1.10.1 (from versions: 0.8.0, 0.9

In [54]:
from gensim.parsing.preprocessing import STOPWORDS

In [55]:
data_tip.head()

user_id             business_id  \
0  AGNUgVwnZUey3gcPCJ76iw  3uLgwr0qeCNMjKenHJwPGQ   
1  NBN4MgHP9D3cw--SnauTkA  QoezRbYQncpRqyrLH6Iqjg   
2  -copOvldyKh1qr-vzkDEvw  MYoRNLb5chwjQe3c_k37Gg   
3  FjMQVZjSqY8syIO-53KFKw  hV-bABTK-glh5wj31ps_Jw   
4  ld0AperBXk1h6UbqmM80zw  _uN0OudeJ3Zl_tf6nxg5ww   

                                                text                date  \
0                     Avengers time with the ladies. 2012-05-18 02:17:21   
1  They have lots of good deserts and tasty cuban... 2013-02-05 18:35:10   
2             It's open even when you think it isn't 2013-08-18 00:56:08   
3                          Very decent fried chicken 2017-06-27 23:05:38   
4             Appetizers.. platter special for lunch 2012-10-06 19:43:09   

   compliment_count  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [56]:
data_review.head()

review_id                 user_id             business_id  \
0  KU_O5udG6zpxOg-VcAEodg  mh_-eMZ6K5RLWhZyISBhwA  XQfwVwDr-v0ZS3_CbbE5Xw   
1  BiTunyQ73aT9WBnpR9DZGw  OyoGAe7OKpv6SyGZT5g77Q  7ATYjTIgM3jUlt4UM3IypQ   
2  saUsX_uimxRlCVr67Z4Jig  8g_iMtfSiwikVnbP2etR0A  YjUWPpI6HXG530lwP-fb2A   
3  AqPFMleE6RsU23_auESxiA  _7bHUi9Uuf5__HHc_Q8guQ  kxX2SOes4o-D3ZQBkiMRfA   
4  Sx8TMOWLNuJBWer-0pcmoA  bcjbaE6dDog4jkNY91ncLQ  e4Vwtrqf-wpJfwesgvdgxQ   

   stars  useful  funny  cool  \
0      3       0      0     0   
1      5       1      0     1   
2      3       0      0     0   
3      5       1      0     1   
4      4       1      0     1   

                                                text                date  
0  If you decide to eat here, just be aware it is... 2018-07-07 22:09:11  
1  I've taken a lot of spin classes over the year... 2012-01-03 15:28:18  
2  Family diner. Had the buffet. Eclectic assortm... 2014-02-05 20:30:30  
3  Wow!  Yummy, different,  delicious.   Our favo... 2015-01-04 00:01:03  
4  Cute interior and owner (?) gave us tour of up... 2017-01-14 20:54:15

In [57]:
data_business.head()

business_id                      name  \
0  Pns2l4eNsfO8kk83dixA6A  Abby Rappoport, LAC, CMQ   
1  mpf3x-BjTdTEA3yCZrAYPw             The UPS Store   
2  tUFrWirKiKi_TAnsVWINQQ                    Target   
3  MTSW4McQd7CbVtyjqoe9mw        St Honore Pastries   
4  mWMc6_wTdE0EUBKIGXDVfA  Perkiomen Valley Brewery   

                           address           city state postal_code  \
0           1616 Chapala St, Ste 2  Santa Barbara    CA       93101   
1  87 Grasso Plaza Shopping Center         Affton    MO       63123   
2             5255 E Broadway Blvd         Tucson    AZ       85711   
3                      935 Race St   Philadelphia    PA       19107   
4                    101 Walnut St     Green Lane    PA       18054   

    latitude   longitude  stars  review_count  is_open  \
0  34.426679 -119.711197    5.0             7        0   
1  38.551126  -90.335695    3.0            15        1   
2  32.223236 -110.880452    3.5            22        0   
3  39.955505  -75.155564    4.0            80        1   
4  40.338183  -75.471659    4.5            13        1   

                                          attributes  \
0                      {'ByAppointmentOnly': 'True'}   
1             {'BusinessAcceptsCreditCards': 'True'}   
2  {'BikeParking': 'True', 'BusinessAcceptsCredit...   
3  {'RestaurantsDelivery': 'False', 'OutdoorSeati...   
4  {'BusinessAcceptsCreditCards': 'True', 'Wheelc...   

                                          categories  \
0  Doctors, Traditional Chinese Medicine, Naturop...   
1  Shipping Centers, Local Services, Notaries, Ma...   
2  Department Stores, Shopping, Fashion, Home & G...   
3  Restaurants, Food, Bubble Tea, Coffee & Tea, B...   
4                          Brewpubs, Breweries, Food   

                                               hours  
0                                               None  
1  {'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ...  
2  {'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ...  
3  {'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...  
4  {'Wednesday': '14:0-22:0', 'Thursday': '16:0-2...

In [58]:
def process_text(document,stopwords=STOPWORDS):
    nlp = spacy.load("en_core_web_sm")
    document = re.sub(r'\s+', ' ', document, flags=re.I) 
    document = re.sub(r'\W', ' ', str(document)) 
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document) 
    document = document.lower() 
    doc_spacy=nlp(document)
    lemma_txt = ["".join(token.lemma_) for token in tqdm.tqdm(doc_spacy)]
    lemma_no_stop_txt = [word for word in lemma_txt if word not in STOPWORDS]
    lemma_no_stop_txt = [word for word in lemma_no_stop_txt if len(word) > 3]
    clean_txt = ' '.join(lemma_no_stop_txt)
    return lemma_no_stop_txt

In [59]:
tip_text = data_tip['text']
review_text = data_review['text']

In [63]:
review_text_preprocessed = review_text.apply(process_text)

100%|██████████| 43/43 [00:00<?, ?it/s]


In [64]:
review_text_preprocessed.head()

0    [decide, aware, hour, begin, multiple, time, w...
1    [spin, class, year, compare, class, body, cycl...
2    [family, diner, buffet, eclectic, assortment, ...
3    [yummy, different, delicious, favorite, lamb, ...
4    [cute, interior, owner,     , tour, upcoming, ...
Name: text, dtype: object

In [95]:
file_path = "unprocessed_2000.csv"

# Export DataFrame to CSV
review_text_preprocessed.to_csv(file_path, index=False)

In [153]:
text = pd.read_csv("preprocessed_2000.csv")

text['text'] = df['text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

text.head()

text
0  decide aware hour begin multiple time want lik...
1  spin class year compare class body cycle nice ...
2  family diner buffet eclectic assortment large ...
3  yummy different delicious favorite lamb curry ...
4  cute interior owner      tour upcoming patio r...

In [117]:
user_counts = data_review['user_id'].value_counts()

# Find the user IDs with the most entries
max_entries_users = user_counts[user_counts == user_counts.max()].index.tolist()

print("User IDs with the most entries:")
for user_id in max_entries_users:
    print(user_id)

User IDs with the most entries:
n-lBS02-3yvlY5Q91mmwDA
758g6NGLp9deCbvowz62Ww
Xw7ZjaGfr0WNVt6s_5KZfA


In [149]:
import pandas as pd

def user_preprocessed(user_id):
    reviews_df = data_review
    preprocessed_texts = text['text']
    user_reviews_df = reviews_df[reviews_df['user_id'] == user_id].copy()
    user_reviews_df['preprocessed_text'] = preprocessed_texts[user_reviews_df.index]
    return user_reviews_df[['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny', 'cool', 'preprocessed_text', 'date']]

print(user_preprocessed('n-lBS02-3yvlY5Q91mmwDA')['preprocessed_text'])


218     hipster unite good time taint despite people a...
1476    katie neighborhood restaurant exist form gener...
1794    want beignet metarie money morning shop dead c...
Name: preprocessed_text, dtype: object


In [150]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min

def cluster_reviews(preprocessed_texts, num_clusters=5):
    # Vectorize the preprocessed text
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix = tfidf_vectorizer.fit_transform(preprocessed_texts)
    
    # Perform K-means clustering
    km = KMeans(n_clusters=num_clusters)
    km.fit(tfidf_matrix)
    
    # Get the cluster centroids
    centroids = km.cluster_centers_
    
    # Find the closest reviews to each centroid
    closest, _ = pairwise_distances_argmin_min(centroids, tfidf_matrix)
    
    # Return the indices of the closest reviews for each cluster
    return closest

In [148]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


def find_similar_users(user_id):
    user_reviews = user_preprocessed(user_id)['preprocessed_text'].values.tolist()  # Extract values and convert to list
    all_user_reviews = review_text_preprocessed.values.tolist()  # Assuming review_text_preprocessed is a Series

    # Flatten the list of lists into a single list of strings for all user reviews
    all_user_reviews_flat = [review for sublist in all_user_reviews for review in sublist]

    # Flatten the list of lists into a single list of strings for user's reviews
    user_reviews_flat = [review for sublist in user_reviews for review in sublist]

    # Calculate TF-IDF vectors for the user's reviews and all user reviews
    tfidf_vectorizer = TfidfVectorizer()
    tfidf_matrix_user = tfidf_vectorizer.fit_transform(user_reviews_flat)
    tfidf_matrix_all_users = tfidf_vectorizer.transform(all_user_reviews_flat)
    
    # Calculate cosine similarity between the user's TF-IDF vector and all other users' TF-IDF vectors
    similarities = cosine_similarity(tfidf_matrix_user, tfidf_matrix_all_users)
    
    # Find the indices of top 10 similar users
    similar_users_indices = np.argsort(similarities[0])[-11:-1][::-1]
    
    # Fetch user IDs corresponding to the similar indices
    similar_user_ids = [review_text_preprocessed.index[i] for i in similar_users_indices]
    
    # Return list of similar users along with their similarity scores
    similar_users = [(user_id, score) for user_id, score in zip(similar_user_ids, similarities[0][similar_users_indices])]
    return similar_users

print(find_similar_users("OyoGAe7OKpv6SyGZT5g77Q"))

print(find_similar_users("Xw7ZjaGfr0WNVt6s_5KZfA"))

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [162]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf_vectorizer = TfidfVectorizer()



def similar_reviews(user_id):
    # Assuming 'text' is a list of review texts
    tfidf_review = tfidf_vectorizer.fit_transform(text['text'])

    # Assuming 'user_preprocessed' is a function that preprocesses user reviews
    user_reviews = user_preprocessed(user_id)['preprocessed_text']
    tfidf_user_reviews = tfidf_vectorizer.transform(user_reviews)

    # Compute cosine similarity between user reviews and all reviews
    user_review_cos = cosine_similarity(tfidf_user_reviews, tfidf_review)

    print(user_review_cos)

    # Get indices of top similar reviews
    sorted_review_indices = sorted(range(len(user_review_cos[0])), key=lambda i: user_review_cos[0][i], reverse=True)[:10]

    print(sorted_review_indices)


    return sorted_review_indices

similar_reviews("Xw7ZjaGfr0WNVt6s_5KZfA")

similar_reviews("Xw7ZjaGfr0WNVt6s_5KZfA")


[[0.07097106 0.02387154 0.0523037  ... 0.06263954 0.03740334 0.02357899]
 [0.06616022 0.03516763 0.06729291 ... 0.05807554 0.05078063 0.01769519]
 [0.0647351  0.01564077 0.01837105 ... 0.02704838 0.2028856  0.01541652]]
[381, 320, 773, 323, 671, 1707, 944, 157, 1868, 1846]
[[0.07097106 0.02387154 0.0523037  ... 0.06263954 0.03740334 0.02357899]
 [0.06616022 0.03516763 0.06729291 ... 0.05807554 0.05078063 0.01769519]
 [0.0647351  0.01564077 0.01837105 ... 0.02704838 0.2028856  0.01541652]]
[381, 320, 773, 323, 671, 1707, 944, 157, 1868, 1846]


[381, 320, 773, 323, 671, 1707, 944, 157, 1868, 1846]

In [163]:
def get_recommendation(top, df_all, scores):
  recommendation = pd.DataFrame(columns = ['user_id', 'business_id',  'stars', 'text', "scores"])
  count = 0
  for i in top:
      recommendation.at[count, 'user_id'] = df_all['user_id']
      recommendation.at[count, 'business_id'] = df_all['business_id'][i]
      recommendation.at[count, 'stars'] = df_all['stars'][i]
      recommendation.at[count, 'text'] = df_all['text'][i]
      recommendation.at[count, 'score'] =  scores[count]
      count += 1
  return recommendation

In [166]:
top_similar_reviews = data_review.iloc[similar_reviews("Xw7ZjaGfr0WNVt6s_5KZfA")]
print(top_similar_reviews)

[[0.07097106 0.02387154 0.0523037  ... 0.06263954 0.03740334 0.02357899]
 [0.06616022 0.03516763 0.06729291 ... 0.05807554 0.05078063 0.01769519]
 [0.0647351  0.01564077 0.01837105 ... 0.02704838 0.2028856  0.01541652]]
[381, 320, 773, 323, 671, 1707, 944, 157, 1868, 1846]
                   review_id                 user_id             business_id  \
381   MWUGmzyXVIlG2NwvzX0q4Q  Xw7ZjaGfr0WNVt6s_5KZfA  i-tDq8zC7ZmSqSbg_7oddA   
320   GVoXS_AdNzSUbyNcoErdZQ  rqYkeGG9PBAdMRDvTMCmfw  MVmJuns9ZD9QLGltc0Am8g   
773   IZtEteas_Oruk0skO4BaSA  DUgvASMlwPxHKe6LZSmO4w  OHzX-ZD9qyoeoxR8Z0dlIA   
323   EYtd1U-fzMWpo-zxMuI5Tw  ChoyWqiqMfKDYuqMKycnpw  yN6jZyG1G1FG_HCZQlJZ1g   
671   Cum9y9Vw0kY4YDvjmgTxBw  1DuUJT5NEEE_JWe6iBPjqA  oQ5CPRt0R3AzFvcjNOqB1w   
1707  VIobe63lPQYn5FkKVPC45Q  IT_fB04jq2rceZQYc7sKVA  Zi-F-YvyVOK0k5QD7lrLOg   
944   aQrkqLr6ualAe94-YwYXiQ  2yow2jF1U5s2Mv-5aeLhWg  tQ6VNQ9ezkxRE4bvu9WShQ   
157   TgDp1TErom3UNglKhDy2uw  zUB7xoTlhbg7_ofHg8Qp0w  W8Z4rXYkmZlEVSaxIVjyvg   
1868  

In [136]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

def recommend_restaurants(user_id):
    user_reviews = user_preprocessed(user_id)['preprocessed_text']    
    ratings = data_review['stars']
    # Split user's reviews into training and testing data
    X_train, X_test, y_train, y_test = train_test_split(review_text_preprocessed, ratings, test_size=0.5)
    
    # Train Naive Bayes classifier with SVM
    classifier = Pipeline([
        ('tfidf', TfidfVectorizer()),
        ('clf', MultinomialNB()),
    ])
    classifier.fit(X_train, y_train)
    
    # Predict ratings for all restaurants
    all_restaurants_ratings = classifier.predict(review_text_preprocessed)
    
    # Get indices of top 10 recommended restaurants
    top_indices = all_restaurants_ratings.argsort()[-10:][::-1]
    
    # Return list of top 10 recommended restaurants
    top_restaurants = [review_text_preprocessed[i] for i in top_indices]
    return top_restaurants

print(recommend_restaurants("Xw7ZjaGfr0WNVt6s_5KZfA"))

AttributeError: 'list' object has no attribute 'lower'